import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "config/material-tailwind-theme-provider";
import ReactQueryClientProvider from "config/ReactQueryClientProvider";
import { createServerSupabaseClient } from "utils/supabase/server";
import AuthProvider from "config/auth-provider";
// import Auth from "components/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = await createServerSupabaseClient();

  // const { data, error } = await supabase
  //   .from('countries')
  //   .select(`
  //     name,
  //     cities (
  //       name
  //     )
  // `)
  // console.log("🚀 ~ countries ~ data:", data)


  const {
    data: { session },
  } = await supabase.auth.getSession();

  console.log('session', session);

  return (
    <ThemeProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
            integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <AuthProvider accessToken={session?.access_token}>
          <ReactQueryClientProvider>
            <body className={inter.className}>
              {children}
            </body>
          </ReactQueryClientProvider>
        </AuthProvider>
      </html>
    </ThemeProvider>
  );
}